# podman play kube mastodon-pod.yml --configmap=mastodon-secrets.yml --replace
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mastodon
  name: mastodon
spec:
  containers:
    - name: postgres
      image: docker.io/library/postgres
      restart: always
      livenessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
        initialDelaySeconds: 45
        periodSeconds: 15
      env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: PGDATA
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: PGDATA
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: PGSECRET
              key: POSTGRES_PASSWORD
    - name: redis
      image: docker.io/library/redis
      restart: always
      livenessProbe:
        exec:
          command:
            - redis-cli
            - ping
        initialDelaySeconds: 5
        periodSeconds: 5