# podman kube play mastodon-deployment.yml --configmap=mastodon-config.yml --replace
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: masto
  name: masto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: masto
  template:
    metadata:
      labels:
        app: masto
    spec:
      volumes:
        - name: pg-storage
          hostPath:
            path: /opt/mastodoncio/data/postgres
            type: DirectoryOrCreate
        - name: pg-shm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: redis-storage
          hostPath:
            path: /opt/mastodoncio/data/redis
            type: DirectoryOrCreate
      containers:
        - name: postgres
          image: docker.io/library/postgres
          restartPolicy: Always
          volumeMounts:
            - name: pg-storage
              mountPath: /var/lib/postgresql/data
            - name: pg-shm
              mountPath: /dev/shm
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 45
            periodSeconds: 15
          envFrom:
            - configMapRef:
                name: PGDATA
        - name: redis
          image: docker.io/library/redis
          restartPolicy: Always
          volumeMounts:
            - name: redis-storage
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
