# podman kube play mastodon-pod.yml --configmap=mastodon-config.yml --replace
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mastodon
  name: mastodon
spec:
  volumes:
    - name: pg-storage
      hostPath:
        path: /opt/mastodoncio/data/postgres
        type: DirectoryOrCreate
    - name: pg-shm
      emptyDir:
        medium: Memory
        sizeLimit: 1Gi
    - name: redis-storage
      hostPath:
        path: /opt/mastodoncio/data/redis
        type: DirectoryOrCreate
  containers:
    - name: postgres
      image: docker.io/library/postgres
      restart: always
      volumeMounts:
        - name: pg-storage
          mountPath: /var/lib/postgresql/data
        - name: pg-shm
          mountPath: /dev/shm
      livenessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
        initialDelaySeconds: 45
        periodSeconds: 15
      env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: PGDATA
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: PGDATA
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: PGSECRET
              key: POSTGRES_PASSWORD
    - name: redis
      image: docker.io/library/redis
      restart: always
      volumeMounts:
        - name: redis-storage
          mountPath: /data
      livenessProbe:
        exec:
          command:
            - redis-cli
            - ping
        initialDelaySeconds: 5
        periodSeconds: 5