---
- name: Instalação das dependências da máquina
  hosts: all
  become: true
  gather_facts: false

  handlers:
  - name: Reboot
    reboot:

  tasks:
    - name: Instalação do dnf-utils e do epel-release
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - dnf-utils
        - epel-release

    - name: Atualização do sistema
      package:
        name: "*"
        state: latest

    - name: Bota o SELinux no modo permissivo, loga ações que podem ser bloqueadas
      selinux:
        policy: targeted
        state: permissive

    - name: Checa se um reboot é necessário
      command: needs-restarting -r
      register: reg_reboot_required
      ignore_errors: yes
      failed_when: false
      changed_when: reg_reboot_required.rc != 0
      notify:
        - Reboot

    - name: Instalação do Firewalld
      package:
        name: firewalld
        state: latest

    - name: Habilitação do socket do firewalld
      systemd:
        name: firewalld
        state: started
        enabled: true

    - name: Configuração da Zona Externa
      firewalld:
        zone: public
        state: enabled
        interface: enp0s3
        permanent: true
        immediate: true

    - name: Configuração das regras iniciais do Firewalld
      firewalld:
        service: ssh
        state: enabled
        zone: public
        immediate: true
        permanent: true

    - name: Instalação do cockpit e do plugin de métricas do cockpit
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - cockpit
        - cockpit-pcp

    - name: Habilitação do socket do cockpit
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - cockpit.socket
        - pmlogger.service

    - name: Criação de usuário para acesso ao cockpit
      user:
        name: mastodoncio
        password: "{{ 'password' | password_hash('sha512') }}"
        groups: wheel
        append: true
        state: present
        createhome: true
        shell: /bin/bash
        update_password: on_create
      register: reg_usuario

    - name: Liberação do Cockpit no Firewalld
      firewalld:
        service: cockpit
        state: enabled
        zone: public
        immediate: true
        permanent: true