---
 - name: Instalação das dependências da máquina
   hosts: all
   become: true
   tasks:

    - name: Desabilitação (temporária) do AppArmor
      systemd:
        name: apparmor
        state: stopped
        enabled: false

    - name: Atualização do sistema
      apt:
        upgrade: 'yes'
        update_cache: true

    - name: Instalação do UFW
      apt:
        name: ufw
        state: latest

    - name: Configuração das regras iniciais do UFW
      ufw:
        rule: allow
        port: "22"

    - name: Habilitação do UFW
      ufw:
        state: enabled
        policy: reject

    - name: Instalação do cockpit
      apt:
        name: cockpit
        state: latest

    - name: Instalação do plugin de métricas do cockpit
      apt:
        name: cockpit-pcp
        state: latest

    - name: Habilitação do socket do cockpit
      systemd:
        name: cockpit.socket
        state: started
        enabled: true
    
    - name: Criação de usuário para acesso ao cockpit
      user:
        name: mastodoncio
        password: "{{ 'password' | password_hash('sha512') }}"
        groups: sudo
        append: true
        state: present
        createhome: true
        shell: /bin/bash
        update_password: on_create
      register: mastodoncio

    - name: Liberação do Cockpit no UFW
      ufw:
        rule: allow
        port: "9090"