---
 - name: Instalação do Podman e suas dependências
   hosts: all
   become: true
   tasks:

    - name: Instalação do UFW
      apt:
        name:
          - podman
          - cockpit-podman
        state: latest

    - name: Habilitação do Podman
      systemd:
        name: podman
        state: started
        enabled: true