---
 - name: Instalação do OpenVPN e suas dependências
   hosts: all
   become: true
   gather_facts: false
   tasks:

    - name: Instalação das dependências do OpenVPN
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - apt-transport-https

    - name: Instalação da chave pública do repositório do OpenVPN
      apt_key:
        url: https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
        state: present
    
    - name: Instalação do repositório do OpenVPN
      apt_repository:
        repo: deb https://swupdate.openvpn.net/community/openvpn3/repos lunar main
        state: present
        update_cache: yes

    - name: Instalação do OpenVPN
      package:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - openvpn3
        - easy-rsa
    
    - name: Criação da pasta de geração das chaves privadas
      file:
        path: /opt/mastodoncio/openvpn/easy-rsa/
        state: directory
    
    - name: Criação do PKI
      command: /usr/share/easy-rsa/easyrsa init-pki
      args:
        chdir: /opt/mastodoncio/openvpn/easy-rsa/
        creates: /opt/mastodoncio/openvpn/easy-rsa/pki

    - name: Geração do DH para negociação de chaves
      command: /usr/share/easy-rsa/easyrsa gen-dh
      args:
        chdir: /opt/mastodoncio/openvpn/easy-rsa/
        creates: /opt/mastodoncio/openvpn/easy-rsa/pki/dh.pem
 
    - name: Criação do env para o easy-rsa
      copy:
        dest: /opt/mastodoncio/openvpn/easy-rsa/pki/vars
        content: |
          set_var EASYRSA_REQ_COUNTRY    "BR"
          set_var EASYRSA_REQ_PROVINCE   "Parana"
          set_var EASYRSA_REQ_CITY       "Curitiba"
          set_var EASYRSA_REQ_ORG        "NuvemLGBT"
          set_var EASYRSA_REQ_EMAIL      "vndmtrx@duck.com"
          set_var EASYRSA_REQ_OU         "Mastodon"
          set_var EASYRSA_ALGO           "ec"
          set_var EASYRSA_DIGEST         "sha512"
          set_var EASYRSA_REQ_CN         "MastoServer"

    - name: Geração da chave da autoridade certificadora
      command: /usr/share/easy-rsa/easyrsa --batch build-ca nopass
      args:
        chdir: /opt/mastodoncio/openvpn/easy-rsa/
        creates: /opt/mastodoncio/openvpn/easy-rsa/pki/ca.crt

    - name: Geração da requisição do certificado do servidor
      command: /usr/share/easy-rsa/easyrsa --batch gen-req mastoserver nopass
      args:
        chdir: /opt/mastodoncio/openvpn/easy-rsa/
        creates: /opt/mastodoncio/openvpn/easy-rsa/pki/reqs/mastoserver.req

    - name: Assinatura do certificado do servidor
      command: /usr/share/easy-rsa/easyrsa --batch sign-req server mastoserver
      args:
        chdir: /opt/mastodoncio/openvpn/easy-rsa/
        creates: /opt/mastodoncio/openvpn/easy-rsa/pki/issued/mastoserver.crt